apiVersion: apps/v1
kind: Deployment
metadata:
  name: viperaveilelo
  namespace: viperaveil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: viperaveilelo
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: viperaveilelo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - image: awesomejack295/viperaveilelo
        name: viperaveilelo
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
      imagePullSecrets:
       - name: dockersecret
      restartPolicy: Always