apiVersion: v1
kind: Service
metadata:
  name: viperaveilelo
  labels:
    app: viperaveilelo
  namespace: viperaveil
spec:
  selector:
    app: viperaveilelo
  ports:
    - name: tcp5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  sessionAffinity: None
  type: ClusterIP