apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-viperaelo
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres-viperaelo
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-viperaelo
    spec:
      containers:
        - name: postgres-viperaelo
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          image: postgres:12
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-viperaelo-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: viperaelo-data-longhorn