apiVersion: v1
kind: Service
metadata:
  name: viperaveilelogamemanager
  labels:
    app: viperaveilelogamemanager
  namespace: viperaveil
spec:
  selector:
    app: viperaveilelogamemanager
  ports:
    - name: tcp80
      port: 80
      protocol: TCP
      targetPort: 80
  sessionAffinity: None
  type: ClusterIP