apiVersion: v1
kind: Service
metadata:
  name: vipera-elo-db
  labels:
    app: vipera-elo-db
  namespace: viperaveil
spec:
  selector:
    app: vipera-elo-db
  ports:
    - name: tcp80
      port: 80
      protocol: TCP
      targetPort: 80
    - name: tcp443
      port: 443
      protocol: TCP
      targetPort: 443
  sessionAffinity: None
  type: ClusterIP